### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by tohaosipow** [asikpro13/ProjectLyceym#1]
1.Убрать внутри папки Code картинку.
2. Посмотреть отчет и поправить немного код к PEP8:
************* Module Code
Code/__init__.py:1:0: C0304: Final newline missing (missing-final-newline)
Code/__init__.py:1:0: C0103: Module name "Code" doesn't conform to snake_case naming style (invalid-name)
Code/__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module Code.Registration
Code/Registration.py:1:0: C0103: Module name "Registration" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/Registration.py:15:8: C0103: Attribute name "db" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:24:8: C0103: Attribute name "labelRegistr" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:25:8: C0103: Attribute name "labelWarRegistr" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:26:8: C0103: Attribute name "labelLogin" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:27:8: C0103: Attribute name "labelPassword" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:28:8: C0103: Attribute name "lineEditForLogin" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:29:8: C0103: Attribute name "lineEditForPassword" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:30:8: C0103: Attribute name "buttonForRegistr" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:11:0: C0115: Missing class docstring (missing-class-docstring)
Code/Registration.py:11:0: R0902: Too many instance attributes (12/7) (too-many-instance-attributes)
Code/Registration.py:16:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/Registration.py:34:4: C0103: Method name "setupUi" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:34:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Registration.py:65:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Registration.py:82:4: C0103: Method name "closeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:82:4: C0103: Argument name "Event" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:82:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Registration.py:82:25: W0613: Unused argument 'Event' (unused-argument)
Code/Registration.py:85:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/Registration.py:85:4: C0116: Missing function or method docstring (missing-function-docstring)
************* Module Code.Auth
Code/Auth.py:1:0: C0103: Module name "Auth" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/Auth.py:12:8: C0103: Attribute name "db" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:23:8: C0103: Attribute name "labelAuth" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:24:8: C0103: Attribute name "labelWarAuth" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:25:8: C0103: Attribute name "labelLogin" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:26:8: C0103: Attribute name "labelPassword" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:27:8: C0103: Attribute name "lineEditForLogin" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:28:8: C0103: Attribute name "lineEditForPassword" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:29:8: C0103: Attribute name "buttonForAuth" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:30:8: C0103: Attribute name "id" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:85:8: C0103: Attribute name "Wind" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:9:0: C0115: Missing class docstring (missing-class-docstring)
Code/Auth.py:9:0: R0902: Too many instance attributes (14/7) (too-many-instance-attributes)
Code/Auth.py:14:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/Auth.py:36:4: C0103: Method name "Auth" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:36:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Auth.py:66:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Auth.py:84:4: C0103: Method name "shopWind" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:84:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Auth.py:88:4: C0103: Method name "closeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:88:4: C0103: Argument name "Event" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:88:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Auth.py:88:25: W0613: Unused argument 'Event' (unused-argument)
Code/Auth.py:91:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/Auth.py:91:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Auth.py:85:8: W0201: Attribute 'Wind' defined outside __init__ (attribute-defined-outside-init)
Code/Auth.py:6:0: C0411: third party import "from PyQt5.QtGui import QFont" should be placed before "from Code.Shop import shopWindow" (wrong-import-order)
Code/Auth.py:6:0: C0412: Imports from package PyQt5 are not grouped (ungrouped-imports)
************* Module Code.config
Code/config.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/config.py:1:0: C0103: Constant name "backgroundMain" doesn't conform to UPPER_CASE naming style (invalid-name)
Code/config.py:2:0: C0103: Constant name "backgroundSide" doesn't conform to UPPER_CASE naming style (invalid-name)
Code/config.py:4:0: C0103: Constant name "buttonAuth" doesn't conform to UPPER_CASE naming style (invalid-name)
Code/config.py:16:0: C0103: Constant name "buttonRegistration" doesn't conform to UPPER_CASE naming style (invalid-name)
Code/config.py:29:0: C0103: Constant name "buttonWindowClose" doesn't conform to UPPER_CASE naming style (invalid-name)
Code/config.py:46:0: C0103: Constant name "buttonWindowHide" doesn't conform to UPPER_CASE naming style (invalid-name)
************* Module Code.LK
Code/LK.py:1:0: C0103: Module name "LK" doesn't conform to snake_case naming style (invalid-name)
Code/LK.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/LK.py:4:0: C0103: Class name "LK_window" doesn't conform to PascalCase naming style (invalid-name)
Code/LK.py:54:8: C0103: Attribute name "pushButton" doesn't conform to snake_case naming style (invalid-name)
Code/LK.py:57:8: C0103: Attribute name "comboBox" doesn't conform to snake_case naming style (invalid-name)
Code/LK.py:4:0: C0115: Missing class docstring (missing-class-docstring)
Code/LK.py:4:0: R0902: Too many instance attributes (12/7) (too-many-instance-attributes)
Code/LK.py:7:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/LK.py:10:4: C0103: Method name "setupUi" doesn't conform to snake_case naming style (invalid-name)
Code/LK.py:10:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/LK.py:10:4: R0915: Too many statements (52/50) (too-many-statements)
Code/LK.py:64:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/LK.py:64:4: C0116: Missing function or method docstring (missing-function-docstring)
************* Module Code.AddProduct
Code/AddProduct.py:83:0: C0301: Line too long (145/120) (line-too-long)
Code/AddProduct.py:95:0: C0301: Line too long (148/120) (line-too-long)
Code/AddProduct.py:1:0: C0103: Module name "AddProduct" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/AddProduct.py:16:0: C0103: Class name "addProductWindow" doesn't conform to PascalCase naming style (invalid-name)
Code/AddProduct.py:20:8: C0103: Attribute name "db" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:27:8: C0103: Attribute name "pushButton" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:38:8: C0103: Attribute name "lineEdit" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:41:8: C0103: Attribute name "lineEdit_2" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:59:8: C0103: Attribute name "pushButton_2" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:70:8: C0103: Attribute name "spinBox" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:74:8: C0103: Attribute name "spinBox_2" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:16:0: C0115: Missing class docstring (missing-class-docstring)
Code/AddProduct.py:16:0: R0902: Too many instance attributes (17/7) (too-many-instance-attributes)
Code/AddProduct.py:21:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/AddProduct.py:24:4: C0103: Method name "setupUi" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:24:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/AddProduct.py:24:4: R0915: Too many statements (51/50) (too-many-statements)
Code/AddProduct.py:82:4: C0103: Method name "addPhoto" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:82:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/AddProduct.py:90:4: C0103: Method name "createProduct" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:90:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/AddProduct.py:102:4: C0103: Method name "closeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:102:4: C0103: Argument name "Event" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:102:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/AddProduct.py:102:25: W0613: Unused argument 'Event' (unused-argument)
Code/AddProduct.py:106:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/AddProduct.py:106:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/AddProduct.py:83:8: W0201: Attribute 'fname' defined outside __init__ (attribute-defined-outside-init)
Code/AddProduct.py:85:8: W0201: Attribute 'pixmap' defined outside __init__ (attribute-defined-outside-init)
Code/AddProduct.py:86:8: W0201: Attribute 'pixmap' defined outside __init__ (attribute-defined-outside-init)
Code/AddProduct.py:13:0: C0411: standard import "import shutil" should be placed before "from PyQt5 import QtCore, QtGui, QtWidgets" (wrong-import-order)
************* Module Code.Main
Code/Main.py:1:0: C0103: Module name "Main" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/Main.py:18:0: C0103: Class name "Main_Auth" doesn't conform to PascalCase naming style (invalid-name)
Code/Main.py:44:8: C0103: Attribute name "Auth" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:52:8: C0103: Attribute name "Registration" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:73:8: C0103: Attribute name "Registr" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:18:0: C0115: Missing class docstring (missing-class-docstring)
Code/Main.py:20:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/Main.py:32:4: C0103: Method name "setupUi" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:32:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Main.py:64:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:64:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Main.py:68:4: C0103: Method name "showWindowAuth" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:68:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Main.py:72:4: C0103: Method name "showWindowRegistration" doesn't conform to snake_case naming style (invalid-name)
Code/Main.py:72:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Main.py:69:8: W0201: Attribute 'Auth' defined outside __init__ (attribute-defined-outside-init)
Code/Main.py:73:8: W0201: Attribute 'Registr' defined outside __init__ (attribute-defined-outside-init)
Code/Main.py:14:0: C0411: standard import "import sys" should be placed before "from PyQt5.QtCore import QRect, Qt, QCoreApplication, QMetaObject" (wrong-import-order)
************* Module Code.DelProduct
Code/DelProduct.py:1:0: C0103: Module name "DelProduct" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/DelProduct.py:12:8: C0103: Attribute name "db" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:30:8: C0103: Attribute name "ok" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:8:0: C0115: Missing class docstring (missing-class-docstring)
Code/DelProduct.py:13:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/DelProduct.py:26:4: C0103: Method name "delUI" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:26:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/DelProduct.py:40:4: C0103: Method name "delProduct" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:40:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/DelProduct.py:44:4: C0103: Method name "closeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:44:4: C0103: Argument name "Event" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:44:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/DelProduct.py:44:25: W0613: Unused argument 'Event' (unused-argument)
Code/DelProduct.py:48:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/DelProduct.py:48:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/DelProduct.py:1:0: W0611: Unused QFrame imported from PyQt5.QtWidgets (unused-import)
Code/DelProduct.py:1:0: W0611: Unused QLineEdit imported from PyQt5.QtWidgets (unused-import)
Code/DelProduct.py:5:0: W0611: Unused QFont imported from PyQt5.QtGui (unused-import)
Code/DelProduct.py:5:0: C0411: third party import "from PyQt5.QtGui import QFont" should be placed before "from Code.ButtonsForWindow import MyBar" (wrong-import-order)
Code/DelProduct.py:5:0: C0412: Imports from package PyQt5 are not grouped (ungrouped-imports)
************* Module Code.Shop
Code/Shop.py:19:0: W0311: Bad indentation. Found 12 spaces, expected 8 (bad-indentation)
Code/Shop.py:20:0: W0311: Bad indentation. Found 16 spaces, expected 12 (bad-indentation)
Code/Shop.py:21:0: W0311: Bad indentation. Found 20 spaces, expected 16 (bad-indentation)
Code/Shop.py:22:0: W0311: Bad indentation. Found 12 spaces, expected 8 (bad-indentation)
Code/Shop.py:118:0: C0301: Line too long (226/120) (line-too-long)
Code/Shop.py:119:0: C0301: Line too long (133/120) (line-too-long)
Code/Shop.py:122:0: C0301: Line too long (128/120) (line-too-long)
Code/Shop.py:123:0: C0301: Line too long (148/120) (line-too-long)
Code/Shop.py:128:0: C0301: Line too long (128/120) (line-too-long)
Code/Shop.py:129:0: C0301: Line too long (146/120) (line-too-long)
Code/Shop.py:207:0: C0301: Line too long (145/120) (line-too-long)
Code/Shop.py:210:0: C0301: Line too long (125/120) (line-too-long)
Code/Shop.py:223:0: C0304: Final newline missing (missing-final-newline)
Code/Shop.py:1:0: C0103: Module name "Shop" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/Shop.py:12:0: C0115: Missing class docstring (missing-class-docstring)
Code/Shop.py:15:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/Shop.py:18:4: C0103: Method name "mousePressEvent" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:18:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:22:12: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/Shop.py:25:0: C0103: Class name "shopWindow" doesn't conform to PascalCase naming style (invalid-name)
Code/Shop.py:28:8: C0103: Attribute name "id" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:29:8: C0103: Attribute name "db" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:30:8: C0103: Attribute name "listWarning" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:35:8: C0103: Attribute name "buttonForLK" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:37:8: C0103: Attribute name "buttonForAddProduct" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:40:8: C0103: Attribute name "buttonForCreateCheck" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:41:8: C0103: Attribute name "lineEditForSearch" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:42:8: C0103: Attribute name "tableWidget" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:149:8: C0103: Attribute name "LK" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:153:8: C0103: Attribute name "addWind" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:157:8: C0103: Attribute name "delWind" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:25:0: C0115: Missing class docstring (missing-class-docstring)
Code/Shop.py:25:0: R0902: Too many instance attributes (16/7) (too-many-instance-attributes)
Code/Shop.py:31:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/Shop.py:47:4: C0103: Method name "setupUi" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:47:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:97:4: C0103: Method name "checkCount" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:97:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:110:4: C0103: Method name "showError" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:110:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:148:4: C0103: Method name "openLKWindow" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:148:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:152:4: C0103: Method name "openAddProductWindow" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:152:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:156:4: C0103: Method name "openDelProductWindow" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:156:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:160:4: C0103: Method name "clickedRow" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:160:4: C0103: Argument name "r" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:160:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:160:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:165:4: C0103: Method name "updateTable" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:165:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:174:16: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:189:4: C0103: Method name "checkError" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:189:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:198:8: W0622: Redefining built-in 'id' (redefined-builtin)
Code/Shop.py:196:4: C0103: Method name "updateProduct" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:196:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:198:8: C0103: Variable name "id" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:206:4: C0103: Method name "resizeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:206:4: C0103: Argument name "Event" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:206:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:206:26: W0613: Unused argument 'Event' (unused-argument)
Code/Shop.py:216:4: C0103: Method name "retranslateUi" doesn't conform to snake_case naming style (invalid-name)
Code/Shop.py:216:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/Shop.py:149:8: W0201: Attribute 'LK' defined outside __init__ (attribute-defined-outside-init)
Code/Shop.py:153:8: W0201: Attribute 'addWind' defined outside __init__ (attribute-defined-outside-init)
Code/Shop.py:157:8: W0201: Attribute 'delWind' defined outside __init__ (attribute-defined-outside-init)
Code/Shop.py:161:8: W0201: Attribute 'row' defined outside __init__ (attribute-defined-outside-init)
************* Module Code.ButtonsForWindow
Code/ButtonsForWindow.py:68:0: C0304: Final newline missing (missing-final-newline)
Code/ButtonsForWindow.py:1:0: C0103: Module name "ButtonsForWindow" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Code/ButtonsForWindow.py:7:0: C0115: Missing class docstring (missing-class-docstring)
Code/ButtonsForWindow.py:7:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
Code/ButtonsForWindow.py:10:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/ButtonsForWindow.py:14:4: C0103: Method name "setupUI" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:14:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:44:4: C0103: Method name "resizeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:44:4: C0103: Argument name "QResizeEvent" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:44:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:45:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
Code/ButtonsForWindow.py:47:4: C0103: Method name "mousePressEvent" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:47:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:51:4: C0103: Method name "mouseMoveEvent" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:51:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:61:4: C0103: Method name "mouseReleaseEvent" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:61:4: C0103: Argument name "QMouseEvent" doesn't conform to snake_case naming style (invalid-name)
Code/ButtonsForWindow.py:61:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:61:32: W0613: Unused argument 'QMouseEvent' (unused-argument)
Code/ButtonsForWindow.py:64:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:67:4: C0116: Missing function or method docstring (missing-function-docstring)
Code/ButtonsForWindow.py:48:8: W0201: Attribute 'start' defined outside __init__ (attribute-defined-outside-init)
Code/ButtonsForWindow.py:59:12: W0201: Attribute 'start' defined outside __init__ (attribute-defined-outside-init)
Code/ButtonsForWindow.py:49:8: W0201: Attribute 'pressing' defined outside __init__ (attribute-defined-outside-init)
Code/ButtonsForWindow.py:62:8: W0201: Attribute 'pressing' defined outside __init__ (attribute-defined-outside-init)
Code/ButtonsForWindow.py:53:12: W0201: Attribute 'end' defined outside __init__ (attribute-defined-outside-init)
Code/ButtonsForWindow.py:54:12: W0201: Attribute 'movement' defined outside __init__ (attribute-defined-outside-init)
Code/ButtonsForWindow.py:1:0: R0801: Similar lines in 2 files
==Code.Auth:14
==Code.Main:20
        self.layout = QVBoxLayout()  # Создание лэйаута
        self.layout.addWidget(MyBar(self))  # Добавление специального класса в лэйаут
        self.setLayout(self.layout)  # Изменение лэйаута в основном окне
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.addStretch(-1)
        self.setMinimumSize(800, 400)  # Изменение минимального размера окна (duplicate-code)
Code/ButtonsForWindow.py:1:0: R0801: Similar lines in 4 files
==Code.Auth:14
==Code.DelProduct:13
==Code.Main:20
==Code.Registration:16
        self.layout = QVBoxLayout()  # Создание лэйаута
        self.layout.addWidget(MyBar(self))  # Добавление специального класса в лэйаут
        self.setLayout(self.layout)  # Изменение лэйаута в основном окне
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.addStretch(-1) (duplicate-code)

**Comment by asikpro13** [comment]
Закрыл большую часть
